import { Cormorant } from "next/font/google";
import "./globals.css";


const cormorant = Cormorant({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['italic', 'normal'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${cormorant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
